stages:
  - deploy

# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Stage "deploy": Copies the repository to github
# ----------------------------------------------------------------------------------------------------------------------------------------------------
github:
  stage: deploy
  tags:
    - general
    - reggie 
  script:
    - if [ -z "${DO_DEPLOY}" ]; then exit ; fi
    - git clone --single-branch git@gitlab.iag.uni-stuttgart.de:cfdfv/code.git cfdfv_github ; cd cfdfv_github ; git push --mirror git@github.com:flexi-framework/cfdfv.git ; cd ../
