### Deplist auto-generated by builddeps V0.99 ###

analyze/analyze.o: analyze/analyze.f90 \
	analyze/analyze_vars.o \
	euler/boundary/boundary_vars.o \
	euler/equation_vars.o \
	euler/exactfunc.o \
	globals.o \
	initialcondition/initialcondition_vars.o \
	mesh/mesh_vars.o \
	output/output_vars.o \
	readin/readin.o \
	readin/readintools.o \
	reconstruction/reconstruction.o \
	timedisc/timedisc_vars.o 

analyze/analyze_vars.o: analyze/analyze_vars.f90 \
	mesh/mesh_vars.o 

cfdfv.o: cfdfv.f90 \
	analyze/analyze.o \
	euler/boundary/boundary.o \
	euler/equation.o \
	fv/fv.o \
	initialcondition/initialcondition.o \
	linearsolver/linearsolver.o \
	mesh/mesh.o \
	mesh/mesh_vars.o \
	output/output.o \
	output/output_vars.o \
	readin/readin.o \
	readin/readintools.o \
	timedisc/timedisc.o \
	timedisc/timedisc_vars.o 

euler/boundary/boundary.o: euler/boundary/boundary.f90 \
	euler/boundary/boundary_vars.o \
	euler/equation_vars.o \
	euler/exactfunc.o \
	euler/primcons.o \
	globals.o \
	mesh/mesh_vars.o \
	readin/readintools.o 

euler/boundary/boundary_vars.o: euler/boundary/boundary_vars.f90 \
	globals.o 

euler/equation.o: euler/equation.f90 \
	euler/equation_vars.o \
	readin/readintools.o 

euler/equation_vars.o: euler/equation_vars.f90 

euler/exactfunc.o: euler/exactfunc.f90 \
	euler/equation_vars.o \
	euler/flux/exact_riemann.o \
	euler/primcons.o \
	globals.o \
	initialcondition/initialcondition_vars.o \
	mesh/mesh_vars.o 

euler/flux/exact_riemann.o: euler/flux/exact_riemann.f90 

euler/flux/flux_ausmd.o: euler/flux/flux_ausmd.f90 \
	euler/equation_vars.o 

euler/flux/flux_ausmdv.o: euler/flux/flux_ausmdv.f90 \
	euler/equation_vars.o 

euler/flux/fluxcalculation.o: euler/flux/fluxcalculation.f90 \
	euler/boundary/boundary.o \
	euler/equation_vars.o \
	euler/flux/flux_ausmd.o \
	euler/flux/flux_ausmdv.o \
	euler/flux/flux_central.o \
	euler/flux/flux_godunov.o \
	euler/flux/flux_hll.o \
	euler/flux/flux_hllc.o \
	euler/flux/flux_hlle.o \
	euler/flux/flux_lax_friedrichs.o \
	euler/flux/flux_roe.o \
	euler/flux/flux_steger_warming.o \
	euler/flux/flux_van_leer.o \
	euler/primcons.o \
	globals.o \
	linearsolver/linearsolver_vars.o \
	mesh/mesh_vars.o 

euler/flux/flux_central.o: euler/flux/flux_central.f90 \
	euler/equation_vars.o 

euler/flux/flux_godunov.o: euler/flux/flux_godunov.f90 \
	euler/equation_vars.o \
	euler/flux/exact_riemann.o 

euler/flux/flux_hllc.o: euler/flux/flux_hllc.f90 \
	euler/equation_vars.o \
	globals.o 

euler/flux/flux_hlle.o: euler/flux/flux_hlle.f90 \
	euler/equation_vars.o \
	globals.o 

euler/flux/flux_hll.o: euler/flux/flux_hll.f90 \
	euler/equation_vars.o \
	globals.o 

euler/flux/flux_lax_friedrichs.o: euler/flux/flux_lax_friedrichs.f90 \
	euler/equation_vars.o 

euler/flux/flux_roe.o: euler/flux/flux_roe.f90 \
	euler/equation_vars.o 

euler/flux/flux_steger_warming.o: euler/flux/flux_steger_warming.f90 \
	euler/equation_vars.o 

euler/flux/flux_van_leer.o: euler/flux/flux_van_leer.f90 \
	euler/equation_vars.o 

euler/primcons.o: euler/primcons.f90 \
	euler/equation_vars.o \
	globals.o 

euler/source.o: euler/source.f90 \
	euler/equation_vars.o \
	globals.o \
	mesh/mesh_vars.o 

fv/fv.o: fv/fv.f90 \
	analyze/analyze.o \
	euler/boundary/boundary.o \
	euler/flux/fluxcalculation.o \
	euler/primcons.o \
	euler/source.o \
	fv/fv_vars.o \
	globals.o \
	mesh/mesh_vars.o \
	readin/readintools.o \
	reconstruction/reconstruction.o \
	reconstruction/reconstruction_vars.o \
	timedisc/timedisc_vars.o 

fv/fv_vars.o: fv/fv_vars.f90 

globals.o: globals.f90 

initialcondition/initialcondition.o: initialcondition/initialcondition.f90 \
	euler/equation_vars.o \
	euler/exactfunc.o \
	euler/primcons.o \
	globals.o \
	initialcondition/initialcondition_vars.o \
	mesh/mesh_vars.o \
	readin/readin.o \
	readin/readintools.o \
	timedisc/timedisc_vars.o 

initialcondition/initialcondition_vars.o: initialcondition/initialcondition_vars.f90 

linearsolver/linearsolver.o: linearsolver/linearsolver.f90 \
	euler/boundary/boundary.o \
	euler/equation_vars.o \
	euler/exactfunc.o \
	euler/flux/flux_lax_friedrichs.o \
	euler/flux/fluxcalculation.o \
	euler/primcons.o \
	fv/fv.o \
	globals.o \
	linearsolver/linearsolver_vars.o \
	mesh/mesh_vars.o \
	readin/readintools.o \
	timedisc/timedisc_vars.o 

linearsolver/linearsolver_vars.o: linearsolver/linearsolver_vars.f90 

mesh/mesh.o: mesh/mesh.f90 \
	euler/boundary/boundary_vars.o \
	globals.o \
	initialcondition/initialcondition_vars.o \
	mesh/mesh_readin.o \
	mesh/mesh_vars.o \
	output/output.o \
	output/output_cgns.o \
	output/output_vars.o \
	readin/readin.o \
	readin/readintools.o \
	timedisc/timedisc_vars.o 

mesh/mesh_readin.o: mesh/mesh_readin.f90 \
	globals.o \
	mesh/mesh_vars.o \
	readin/readin.o 

mesh/mesh_vars.o: mesh/mesh_vars.f90 \
	euler/boundary/boundary_vars.o \
	globals.o 

output/output_cgns.o: output/output_cgns.f90 \
	euler/boundary/boundary_vars.o \
	euler/equation_vars.o \
	euler/exactfunc.o \
	globals.o \
	mesh/mesh_vars.o \
	output/output_vars.o \
	timedisc/timedisc_vars.o 

output/output.o: output/output.f90 \
	analyze/analyze_vars.o \
	euler/equation_vars.o \
	euler/exactfunc.o \
	globals.o \
	mesh/mesh_vars.o \
	output/output_cgns.o \
	output/output_vars.o \
	readin/readin.o \
	readin/readintools.o \
	timedisc/timedisc_vars.o 

output/output_vars.o: output/output_vars.f90 

readin/isovaryingstring.o: readin/isovaryingstring.f90 

readin/readin.o: readin/readin.f90 \
	analyze/analyze_vars.o \
	euler/equation_vars.o \
	euler/primcons.o \
	globals.o \
	mesh/mesh_vars.o \
	timedisc/timedisc_vars.o 

readin/readintools.o: readin/readintools.f90 \
	globals.o \
	readin/isovaryingstring.o 

reconstruction/limiter.o: reconstruction/limiter.f90 \
	globals.o \
	mesh/mesh_vars.o \
	reconstruction/reconstruction_vars.o 

reconstruction/reconstruction.o: reconstruction/reconstruction.f90 \
	euler/boundary/boundary.o \
	fv/fv_vars.o \
	globals.o \
	mesh/mesh_vars.o \
	reconstruction/limiter.o 

reconstruction/reconstruction_vars.o: reconstruction/reconstruction_vars.f90 

timedisc/calctimestep.o: timedisc/calctimestep.f90 \
	euler/equation_vars.o \
	euler/primcons.o \
	globals.o \
	mesh/mesh_vars.o \
	timedisc/timedisc_vars.o 

timedisc/explicittimestep.o: timedisc/explicittimestep.f90 \
	analyze/analyze.o \
	euler/primcons.o \
	fv/fv.o \
	globals.o \
	mesh/mesh_vars.o \
	timedisc/timedisc_vars.o 

timedisc/implicittimestep.o: timedisc/implicittimestep.f90 \
	analyze/analyze.o \
	euler/primcons.o \
	fv/fv.o \
	globals.o \
	linearsolver/linearsolver.o \
	linearsolver/linearsolver_vars.o \
	mesh/mesh_vars.o 

timedisc/timedisc.o: timedisc/timedisc.f90 \
	analyze/analyze.o \
	analyze/analyze_vars.o \
	globals.o \
	linearsolver/linearsolver_vars.o \
	output/output.o \
	output/output_vars.o \
	readin/readintools.o \
	timedisc/calctimestep.o \
	timedisc/explicittimestep.o \
	timedisc/implicittimestep.o \
	timedisc/timedisc_vars.o 

timedisc/timedisc_vars.o: timedisc/timedisc_vars.f90 

